name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install --upgrade pip ruff bandit
      - run: ruff check . || true
      - run: bandit -q -r . || true
      - name: CLI smoke check
        run: |
          python -c "import importlib; importlib.import_module('prooflens_sign')"
          python -m prooflens_sign --help || true
